CREATE TABLE [EntidadRegulatoria].[ro_rdep_det] (
    [IdEmpresa]                            INT           NOT NULL,
    [Id_Rdep]                              INT           NOT NULL,
    [Secuencia]                            INT           NOT NULL,
    [IdEmpleado]                           NUMERIC (18)  NOT NULL,
    [pe_cedulaRuc]                         VARCHAR (50)  NULL,
    [pe_nombre]                            VARCHAR (100) NULL,
    [pe_apellido]                          VARCHAR (100) NULL,
    [Sueldo]                               FLOAT (53)    NULL,
    [FondosReserva]                        FLOAT (53)    NULL,
    [DecimoTercerSueldo]                   FLOAT (53)    NULL,
    [DecimoCuartoSueldo]                   FLOAT (53)    NULL,
    [Vacaciones]                           FLOAT (53)    NULL,
    [AportePErsonal]                       FLOAT (53)    NULL,
    [GastoAlimentacion]                    FLOAT (53)    NULL,
    [GastoEucacion]                        FLOAT (53)    NULL,
    [GastoSalud]                           FLOAT (53)    NULL,
    [GastoVestimenta]                      FLOAT (53)    NULL,
    [GastoVivienda]                        FLOAT (53)    NULL,
    [Utilidades]                           FLOAT (53)    NULL,
    [IngresoVarios]                        FLOAT (53)    NULL,
    [IngresoPorOtrosEmpleaodres]           FLOAT (53)    NULL,
    [IessPorOtrosEmpleadores]              FLOAT (53)    NULL,
    [ValorImpuestoPorEsteEmplador]         FLOAT (53)    NULL,
    [ValorImpuestoPorOtroEmplador]         FLOAT (53)    NULL,
    [ExoneraionPorDiscapacidad]            FLOAT (53)    NULL,
    [ExoneracionPorTerceraEdad]            FLOAT (53)    NULL,
    [OtrosIngresosRelacionDependencia]     FLOAT (53)    NULL,
    [ImpuestoRentaCausado]                 FLOAT (53)    NULL,
    [ValorImpuestoRetenidoTrabajador]      FLOAT (53)    NULL,
    [ImpuestoRentaAsumidoPorEsteEmpleador] FLOAT (53)    NULL,
    [BaseImponibleGravada]                 FLOAT (53)    NULL,
    [IngresosGravadorPorEsteEmpleador]     FLOAT (53)    NULL,
    CONSTRAINT [PK_ro_rdep_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [Id_Rdep] ASC, [Secuencia] ASC),
    CONSTRAINT [FK_ro_rdep_det_ro_rdep] FOREIGN KEY ([IdEmpresa], [Id_Rdep]) REFERENCES [EntidadRegulatoria].[ro_rdep] ([IdEmpresa], [Id_Rdep]),
    CONSTRAINT [FK_ro_rdep_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado]),
    CONSTRAINT [FK_ro_rdep_tb_empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [dbo].[tb_empresa] ([IdEmpresa])
);

