//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_compras : DbContext
    {
        public Entities_compras()
            : base("name=Entities_compras")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<com_catalogo> com_catalogo { get; set; }
        public virtual DbSet<com_catalogo_tipo> com_catalogo_tipo { get; set; }
        public virtual DbSet<com_comprador> com_comprador { get; set; }
        public virtual DbSet<com_departamento> com_departamento { get; set; }
        public virtual DbSet<com_estado_cierre> com_estado_cierre { get; set; }
        public virtual DbSet<com_ordencompra_local> com_ordencompra_local { get; set; }
        public virtual DbSet<com_parametro> com_parametro { get; set; }
        public virtual DbSet<com_solicitante> com_solicitante { get; set; }
        public virtual DbSet<com_TerminoPago> com_TerminoPago { get; set; }
        public virtual DbSet<vwcom_ordencompra_local_det> vwcom_ordencompra_local_det { get; set; }
        public virtual DbSet<com_ordencompra_local_det> com_ordencompra_local_det { get; set; }
        public virtual DbSet<vwcom_ordencompra_local_detPorIngresar> vwcom_ordencompra_local_detPorIngresar { get; set; }
        public virtual DbSet<com_ordencompra_local_resumen> com_ordencompra_local_resumen { get; set; }
        public virtual DbSet<vwcom_ordencompra_local> vwcom_ordencompra_local { get; set; }
    }
}
