//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_PuntoVta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fa_PuntoVta()
        {
            this.fa_factura = new HashSet<fa_factura>();
            this.fa_guia_remision = new HashSet<fa_guia_remision>();
            this.fa_notaCreDeb = new HashSet<fa_notaCreDeb>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public string cod_PuntoVta { get; set; }
        public string nom_PuntoVta { get; set; }
        public bool estado { get; set; }
        public int IdBodega { get; set; }
        public int IdCaja { get; set; }
        public string IPImpresora { get; set; }
        public Nullable<int> NumCopias { get; set; }
        public bool CobroAutomatico { get; set; }
        public string codDocumentoTipo { get; set; }
        public bool EsElectronico { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_factura> fa_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_guia_remision> fa_guia_remision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fa_notaCreDeb> fa_notaCreDeb { get; set; }
    }
}
