INSERT INTO seg_Usuario_x_Empresa
SELECT 'admin',1,''

insert into seg_Menu_x_Empresa
select 1,IdMenu,'' from seg_Menu

insert into seg_Usuario_x_Empresa
select 'admin',1,''

INSERT INTO [dbo].[tb_sucursal]
           ([IdEmpresa]
           ,[IdSucursal]
           ,[codigo]
           ,[Su_Descripcion]
           ,[Su_CodigoEstablecimiento]
           ,[Su_Ruc]
           ,[Su_JefeSucursal]
           ,[Su_Telefonos]
           ,[Su_Direccion]
           ,[Estado]
           ,[Es_establecimiento]
           ,[IdCtaCble_cxp]
           ,[IdCtaCble_vtaIVA0]
           ,[IdCtaCble_vtaIVA])
select 1,1,'001','MATRIZ','001',NULL,NULL,NULL,NULL,'A',1,NULL,NULL,NULL

insert into seg_usuario_x_tb_sucursal
select 'admin',1,1,''

insert into seg_Menu_x_Empresa_x_Usuario
SELECT 1,'admin',IdMenu,0,0,0 FROM seg_Menu

INSERT INTO [dbo].[tb_bodega]
           ([IdEmpresa]
           ,[IdSucursal]
           ,[IdBodega]
           ,[cod_bodega]
           ,[bo_Descripcion]
           ,[bo_EsBodega]
           ,[Estado]
           ,[IdCtaCtble_Inve])
select 1,1,1,'001','MATRIZ',1,'A',NULL

INSERT [dbo].[ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo] ([IdEmpresa], [CodTipoCbteBan], [IdTipoCbteCble], [IdTipoCbteCble_Anu], [IdCtaCble], [Tipo_DebCred]) VALUES (1, N'CHEQ', 2, 6, NULL, N'D')
INSERT [dbo].[ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo] ([IdEmpresa], [CodTipoCbteBan], [IdTipoCbteCble], [IdTipoCbteCble_Anu], [IdCtaCble], [Tipo_DebCred]) VALUES (1, N'DEPO', 3, 6, NULL, N'C')
INSERT [dbo].[ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo] ([IdEmpresa], [CodTipoCbteBan], [IdTipoCbteCble], [IdTipoCbteCble_Anu], [IdCtaCble], [Tipo_DebCred]) VALUES (1, N'NCBA', 4, 6, NULL, N'C')
INSERT [dbo].[ba_Cbte_Ban_tipo_x_ct_CbteCble_tipo] ([IdEmpresa], [CodTipoCbteBan], [IdTipoCbteCble], [IdTipoCbteCble_Anu], [IdCtaCble], [Tipo_DebCred]) VALUES (1, N'NDBA', 5, 6, NULL, N'D')
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'ANTI_EMPLE', N'0602031001001', 17, N'APRO', N'N', N'0602031001001', 0)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'ANTI_PROVEE', NULL, 17, N'APRO', N'N', NULL, 1)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'FACT_PROVEE', NULL, 17, N'APRO', N'S', NULL, 0)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'LIQ_HAB', NULL, 17, N'APRO', N'N', NULL, 0)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'OTROS_CONC', NULL, 17, N'APRO', N'N', NULL, 0)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'PRESTAMOS', NULL, 17, N'APRO', N'N', NULL, 0)
INSERT [dbo].[cp_orden_pago_tipo_x_empresa] ([IdEmpresa], [IdTipo_op], [IdCtaCble], [IdTipoCbte_OP], [IdEstadoAprobacion], [Buscar_FactxPagar], [IdCtaCble_Credito], [Dispara_Alerta]) VALUES (1, N'VACACIONES', NULL, 17, N'APRO', N'N', NULL, 0)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 1, N'CD', N'DIARIO CONTABLE', N'A', N'S', N'CD        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 2, N'CHE', N'CHEQUE', N'A', N'N', N'CH        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 3, N'DEP', N'DEPOSITO', N'A', N'N', N'DEP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 4, N'NCB', N'NOTA CREDITO BANCARIA', N'A', N'N', N'NCB       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 5, N'NDB', N'NOTA DEBITO BANCARIA', N'A', N'N', N'NDB       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 6, N'ABAN', N'ANULACIONES BANCARIAS', N'A', N'N', N'ABA       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 7, N'CTCXP', N'COMPROBANTE DE PROVEEDOR', N'A', N'N', N'CCP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 8, N'ACTCXP', N'ANULACION  COMPROBANTE PROVEEDOR', N'A', N'N', N'ACP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 9, N'NCCP', N'NOTA CREDITO POR PAGAR', N'A', N'N', N'NCP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 10, N'NDCXP', N'NOTA DEBITO POR PAGAR', N'A', N'N', N'NDP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 11, N'PFXP', N'PROVISION FACTURA X PAGAR', N'A', N'N', N'PF        ', 1, NULL, NULL, NULL, NULL, N'', CAST(N'2015-11-10 00:00:00.000' AS DateTime), N'')
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 12, N'AJCXP', N'AJUSTE DE CTAS. X  PAGAR', N'A', N'N', N'PP        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 13, N'ANCCXP', N'ANULACION CXP  N/C N/D', N'A', N'N', N'ANC       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 14, N'RTXPRV', N'RETENCION POR PROVEEDOR', N'A', N'N', N'RPV       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 15, N'ARTXPR', N'ANULACION RETENCION POR PROVEEDOR', N'A', N'N', N'ARP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 16, N'CPANT', N'CONCILIACION X CXP', N'A', N'N', N'CANT      ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 17, N'CTOP', N'COMPROBANTE ORDEN DE PAGO', N'A', N'N', N'COP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 18, N'ANUOP', N'ANULACION ORDEN PAGO', N'A', N'N', N'AOP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 19, N'CVTA', N'COMPROBANTE DE VENTA X CLIENTE', N'A', N'N', N'CV        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 20, N'N/C', N'NOTAS DE CREDITO X CLIENTE', N'A', N'N', N'N/C       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 21, N'N/D', N'NOTAS DE DEBITO X CLIENTE', N'A', N'N', N'N/D       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 22, N'AVTANCD', N'ANULACION DE CBTES VTA/NC/ND CLIENTE', N'A', N'N', N'AN/D      ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 23, N'INGCAJ', N'INGRESO CAJA', N'A', N'N', N'ICJ       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 24, N'EGRCAJ', N'EGRESO CAJA', N'A', N'N', N'ECJ       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 25, N'AIECAJ', N'ANULACION ING/EGR CAJA', N'A', N'N', N'ACJ       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 26, N'IMP', N'IMPORTACIONES', N'A', N'N', N'IMP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 27, N'AIMP', N'ANULACION IMPORTACIONES', N'A', N'N', N'AIM       ', 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 28, N'COMPR', N'COMPRAS', N'A', N'N', N'CMP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 29, N'COMPR', N'ANULACION DE COMPRAS', N'A', N'N', N'CMP       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 30, N'SI', N'SALDO INICIAL', N'A', N'S', N'SIN       ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 31, N'CM', N'CIERRE DE MES', N'A', N'N', N'CM        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 32, N'RP', N'ROL DE PAGOS', N'A', N'N', N'RP        ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 33, N'DANU', N'ANULACION DE DIARIO CONTABLE', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 34, N'EGXTR', N'EGRESO X TRANSFERENCIA', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 35, N'INGXTR', N'INGRESO X TRANSFERENCIA', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 36, N'CIEANU', N'CIERRE ANUAL', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 37, N'COBR', N'COBRO', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 38, N'ANUCOB', N'ANULACION DE COBROS', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 39, N'PREBAN', N'PRESTAMOS BANCARIOS', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 40, N'ANUCAJ', N'ANULACION DE INGRESO CAJA', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 41, N'ANUEGRCA', N'ANULACION DE EGRESO CAJA', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 42, N'DEPR', N'DEPRECIACIONES', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 43, N'ANUDEPR', N'ANULACION DE DEPRECIACIONES', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 44, N'MAF', N'MEJORA AF', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 45, N'VAF', N'VENTA AF', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 46, N'BAF', N'BAJA AF', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 47, N'RAF', N'RETIRO AF', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 48, N'ANUANT', N'ANULACION DE ANTICIPOS CXP', N'A', N'N', N'          ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 49, N'ANUEG', N'ANULACION DE EGRESO DE INVENTARIO', N'A', N'N', N'ANUEG     ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 50, N'ANUIG', N'ANULACION DE INGRESO DE INVENTARIO', N'A', N'N', N'ANUIG     ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 51, N'EGRIN', N'EGRESO DE INVENTARIO', N'A', N'N', N'EGRIN     ', 49, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 52, N'INGIN', N'INGRESO DE INVENTARIO', N'A', N'N', N'INGIN     ', 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 53, N'ANUCHE', N'ANULACION CHEQUE', N'A', N'N', N'ANUCH     ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte], [CodTipoCbte], [tc_TipoCbte], [tc_Estado], [tc_Interno], [tc_Nemonico], [IdTipoCbte_Anul], [IdUsuario], [Fecha_Transac], [IdUsuarioUltMod], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotiAnula]) VALUES (1, 54, N'NOMINA    ', N'NOMINA                                            ', N'A', N'S', N'NOMIN     ', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'ACTIV', N'ACTIVO                                            ', 1, N'BG', 1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'COSTO', N'COSTOS                                            ', 5, N'ER', 1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'GASTO', N'GASTOS                                            ', 6, N'ER', 1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'INGRE', N'INGRESOS                                          ', 4, N'ER', -1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'OTING', N'OTROS INGRESOS                                    ', 7, N'ER', -1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'PASIV', N'PASIVO                                            ', 2, N'BG', -1, N'A', NULL)
INSERT [dbo].[ct_grupocble] ([IdGrupoCble], [gc_GrupoCble], [gc_Orden], [gc_estado_financiero], [gc_signo_operacion], [Estado], [IdGrupo_Mayor]) VALUES (N'PATRI', N'PATRIMONIO                                        ', 3, N'BG', -1, N'A', NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 1, 2, N'Nivel 1', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 2, 2, N'Nivel 2', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 3, 3, N'Nivel 3', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 4, 3, N'Nivel 4', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 5, 3, N'Nivel 5', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[ct_plancta_nivel] ([IdEmpresa], [IdNivelCta], [nv_NumDigitos], [nv_Descripcion], [Estado], [IdUsuario], [Fecha_Transaccion], [IdUsuarioUltModi], [Fecha_UltMod], [IdUsuarioUltAnu], [Fecha_UltAnu], [MotivoAnulacion]) VALUES (1, 6, 3, N'Nivel 6', N'A', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CON', N'CONTADO', 0, 1, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE120', N'CREDITO 120 DIAS', 0, 120, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE180', N'CREDITO 180 DIAS', 0, 180, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE240', N'CREDITO 240 DIAS', 0, 0, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE30', N'CREDITO 30 DIAS', 0, 30, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE60', N'CREDITO 60 DIAS', 0, 60, 1)
INSERT [dbo].[fa_TerminoPago] ([IdTerminoPago], [nom_TerminoPago], [Num_Coutas], [Dias_Vct], [estado]) VALUES (N'CRE90', N'CREDITO 90 DIAS', 0, 90, 1)
INSERT [dbo].[tb_sis_Documento_Tipo_x_Empresa] ([IdEmpresa], [codDocumentoTipo], [ApareceComboFac_TipoFact], [ApareceComboFac_Import], [ApareceTalonario], [Descripcion], [Posicion], [ApareceCombo_FileReporte]) VALUES (1, N'FACT', N'0', N'0', N'0', N'0', 0, N'0')
INSERT [dbo].[tb_sis_Documento_Tipo_x_Empresa] ([IdEmpresa], [codDocumentoTipo], [ApareceComboFac_TipoFact], [ApareceComboFac_Import], [ApareceTalonario], [Descripcion], [Posicion], [ApareceCombo_FileReporte]) VALUES (1, N'GUIA', N'0', N'0', N'0', N'0', 0, N'0')
INSERT [dbo].[tb_sis_Documento_Tipo_x_Empresa] ([IdEmpresa], [codDocumentoTipo], [ApareceComboFac_TipoFact], [ApareceComboFac_Import], [ApareceTalonario], [Descripcion], [Posicion], [ApareceCombo_FileReporte]) VALUES (1, N'NTCR', N'0', N'0', N'0', N'0', 0, N'0')
INSERT [dbo].[tb_sis_Documento_Tipo_x_Empresa] ([IdEmpresa], [codDocumentoTipo], [ApareceComboFac_TipoFact], [ApareceComboFac_Import], [ApareceTalonario], [Descripcion], [Posicion], [ApareceCombo_FileReporte]) VALUES (1, N'NTDB', N'0', N'0', N'0', N'0', 0, N'0')
INSERT [dbo].[tb_sis_Documento_Tipo_x_Empresa] ([IdEmpresa], [codDocumentoTipo], [ApareceComboFac_TipoFact], [ApareceComboFac_Import], [ApareceTalonario], [Descripcion], [Posicion], [ApareceCombo_FileReporte]) VALUES (1, N'RETEN', N'0', N'0', N'0', N'0', 0, N'0')
