//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_Conciliacion_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdConciliacion { get; set; }
        public int Secuencia { get; set; }
        public int IdTipocbte { get; set; }
        public string tipo_IngEgr { get; set; }
        public string Referencia { get; set; }
        public bool Seleccionado { get; set; }
        public string Observacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
    
        public virtual ba_Conciliacion ba_Conciliacion { get; set; }
    }
}
