//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_ordencompra_local
    {
        public com_ordencompra_local()
        {
            this.com_ordencompra_local_det = new HashSet<com_ordencompra_local_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public int SecuenciaTipo { get; set; }
        public string Tipo { get; set; }
        public decimal IdProveedor { get; set; }
        public int IdTerminoPago { get; set; }
        public int oc_plazo { get; set; }
        public System.DateTime oc_fecha { get; set; }
        public string oc_observacion { get; set; }
        public string Estado { get; set; }
        public string IdEstadoAprobacion_cat { get; set; }
        public decimal IdDepartamento { get; set; }
        public System.DateTime oc_fechaVencimiento { get; set; }
        public string IdEstado_cierre { get; set; }
        public decimal IdComprador { get; set; }
        public string IdUsuarioAprobacion { get; set; }
        public string MotivoAprobacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual com_catalogo com_catalogo { get; set; }
        public virtual com_comprador com_comprador { get; set; }
        public virtual com_departamento com_departamento { get; set; }
        public virtual com_estado_cierre com_estado_cierre { get; set; }
        public virtual com_TerminoPago com_TerminoPago { get; set; }
        public virtual ICollection<com_ordencompra_local_det> com_ordencompra_local_det { get; set; }
    }
}
