//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_catalogo_tipo
    {
        public com_catalogo_tipo()
        {
            this.com_catalogo = new HashSet<com_catalogo>();
        }
    
        public string IdCatalogocompra_tipo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<com_catalogo> com_catalogo { get; set; }
    }
}
