//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_ConciliacionAnticipo
    {
        public cp_ConciliacionAnticipo()
        {
            this.cp_ConciliacionAnticipoDetAnt = new HashSet<cp_ConciliacionAnticipoDetAnt>();
            this.cp_ConciliacionAnticipoDetCXP = new HashSet<cp_ConciliacionAnticipoDetCXP>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdConciliacion { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdProveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public bool Estado { get; set; }
        public Nullable<decimal> Idcancelacion { get; set; }
        public Nullable<int> IdTipoCbte { get; set; }
        public Nullable<decimal> IdCbteCble { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual cp_proveedor cp_proveedor { get; set; }
        public virtual ICollection<cp_ConciliacionAnticipoDetAnt> cp_ConciliacionAnticipoDetAnt { get; set; }
        public virtual ICollection<cp_ConciliacionAnticipoDetCXP> cp_ConciliacionAnticipoDetCXP { get; set; }
    }
}
