//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_parametros
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> pa_TipoCbte_OG { get; set; }
        public string pa_ctacble_iva { get; set; }
        public Nullable<int> pa_IdTipoCbte_x_Retencion { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public Nullable<int> pa_TipoCbte_NC { get; set; }
        public Nullable<int> pa_TipoCbte_ND { get; set; }
        public Nullable<int> pa_TipoCbte_para_conci_x_antcipo { get; set; }
        public int DiasTransaccionesAFuturo { get; set; }
        public Nullable<bool> SeValidaCtaGasto { get; set; }
    }
}
