//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_anio_fiscal_x_tb_sucursal
    {
        public int IdEmpresa { get; set; }
        public int IdanioFiscal { get; set; }
        public int IdSucursal { get; set; }
        public int IdTipoCbte { get; set; }
        public decimal IdCbteCble { get; set; }
    
        public virtual ct_cbtecble ct_cbtecble { get; set; }
        public virtual ct_anio_fiscal_x_cuenta_utilidad ct_anio_fiscal_x_cuenta_utilidad { get; set; }
    }
}
