//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_ClasificacionEBIT
    {
        public ct_ClasificacionEBIT()
        {
            this.ct_plancta = new HashSet<ct_plancta>();
        }
    
        public int IdClasificacionEBIT { get; set; }
        public string ebit_Codigo { get; set; }
        public string ebit_Descripcion { get; set; }
        public bool AplicaEBIT { get; set; }
        public bool AplicaEBITDA { get; set; }
    
        public virtual ICollection<ct_plancta> ct_plancta { get; set; }
    }
}
