//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_ClasificacionEBIT
    {
        public ct_ClasificacionEBIT()
        {
            this.ct_plancta = new HashSet<ct_plancta>();
        }
    
        public int IdClasificacionEBIT { get; set; }
        public string ebit_Codigo { get; set; }
        public string ebit_Descripcion { get; set; }
        public bool AplicaEBIT { get; set; }
        public bool AplicaEBITDA { get; set; }
    
        public virtual ICollection<ct_plancta> ct_plancta { get; set; }
    }
}
