//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_periodo_x_tb_modulo
    {
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public string IdModulo { get; set; }
        public bool Cerrado { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaTransac { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
    
        public virtual ct_periodo ct_periodo { get; set; }
    }
}
