//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_periodo_x_tb_modulo
    {
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public string IdModulo { get; set; }
        public bool Cerrado { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaTransac { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
    
        public virtual ct_periodo ct_periodo { get; set; }
    }
}
