//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_punto_cargo
    {
        public ct_punto_cargo()
        {
            this.ct_cbtecble_det = new HashSet<ct_cbtecble_det>();
            this.ct_cbtecble_Plantilla_det = new HashSet<ct_cbtecble_Plantilla_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdPunto_cargo { get; set; }
        public string cod_punto_cargo { get; set; }
        public string nom_punto_cargo { get; set; }
        public bool Estado { get; set; }
        public int IdPunto_cargo_grupo { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string IdUsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<ct_cbtecble_det> ct_cbtecble_det { get; set; }
        public virtual ICollection<ct_cbtecble_Plantilla_det> ct_cbtecble_Plantilla_det { get; set; }
        public virtual ct_punto_cargo_grupo ct_punto_cargo_grupo { get; set; }
    }
}
