//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_LiquidacionRetProvDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int Secuencia { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public int secuencial { get; set; }
        public string IdCobro_tipo { get; set; }
        public double Valor { get; set; }
    
        public virtual cxc_cobro cxc_cobro { get; set; }
        public virtual cxc_cobro_det cxc_cobro_det { get; set; }
        public virtual cxc_LiquidacionRetProv cxc_LiquidacionRetProv { get; set; }
    }
}
