//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Ing_Egr_Inven
    {
        public in_Ing_Egr_Inven()
        {
            this.in_Ajuste = new HashSet<in_Ajuste>();
            this.in_Ajuste1 = new HashSet<in_Ajuste>();
            this.in_Consignacion = new HashSet<in_Consignacion>();
            this.in_devolucion_inven = new HashSet<in_devolucion_inven>();
            this.in_devolucion_inven1 = new HashSet<in_devolucion_inven>();
            this.in_Ing_Egr_Inven_det = new HashSet<in_Ing_Egr_Inven_det>();
            this.in_transferencia = new HashSet<in_transferencia>();
            this.in_transferencia1 = new HashSet<in_transferencia>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public string signo { get; set; }
        public string CodMoviInven { get; set; }
        public string cm_observacion { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public string IdUsuario { get; set; }
        public string Estado { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdusuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public Nullable<int> IdMotivo_Inv { get; set; }
        public Nullable<decimal> IdResponsable { get; set; }
        public string IdEstadoAproba { get; set; }
        public string IdUsuarioAR { get; set; }
        public Nullable<System.DateTime> FechaAR { get; set; }
        public string IdUsuarioDespacho { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
    
        public virtual ICollection<in_Ajuste> in_Ajuste { get; set; }
        public virtual ICollection<in_Ajuste> in_Ajuste1 { get; set; }
        public virtual ICollection<in_Consignacion> in_Consignacion { get; set; }
        public virtual ICollection<in_devolucion_inven> in_devolucion_inven { get; set; }
        public virtual ICollection<in_devolucion_inven> in_devolucion_inven1 { get; set; }
        public virtual ICollection<in_Ing_Egr_Inven_det> in_Ing_Egr_Inven_det { get; set; }
        public virtual in_Motivo_Inven in_Motivo_Inven { get; set; }
        public virtual ICollection<in_transferencia> in_transferencia { get; set; }
        public virtual ICollection<in_transferencia> in_transferencia1 { get; set; }
    }
}
