//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity_facturacion_electronica : DbContext
    {
        public Entity_facturacion_electronica()
            : base("name=Entity_facturacion_electronica")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vwcp_retencion> vwcp_retencion { get; set; }
        public virtual DbSet<vwcp_retencion_detalle> vwcp_retencion_detalle { get; set; }
        public virtual DbSet<vwfa_factura> vwfa_factura { get; set; }
        public virtual DbSet<vwfa_factura_detalle> vwfa_factura_detalle { get; set; }
        public virtual DbSet<vwfa_factura_impuestos> vwfa_factura_impuestos { get; set; }
        public virtual DbSet<vwfa_guia_remision> vwfa_guia_remision { get; set; }
        public virtual DbSet<vwfa_guia_remision_detalle> vwfa_guia_remision_detalle { get; set; }
        public virtual DbSet<vwfa_guia_remision_x_factura> vwfa_guia_remision_x_factura { get; set; }
        public virtual DbSet<vwfa_nota_credito> vwfa_nota_credito { get; set; }
        public virtual DbSet<vwfa_nota_credito_detalle> vwfa_nota_credito_detalle { get; set; }
        public virtual DbSet<vwfa_nota_credito_impuestos> vwfa_nota_credito_impuestos { get; set; }
        public virtual DbSet<vwfa_nota_debito> vwfa_nota_debito { get; set; }
        public virtual DbSet<vwfa_nota_debito_detalle> vwfa_nota_debito_detalle { get; set; }
        public virtual DbSet<vwfa_nota_debito_impuestos> vwfa_nota_debito_impuestos { get; set; }
    }
}
