//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_biometrico
    {
        public int IdEmpresa { get; set; }
        public int IdBiometrico { get; set; }
        public int IdEquipo { get; set; }
        public string Descripcion { get; set; }
        public string StringConexion { get; set; }
        public string Consulta { get; set; }
        public bool MarcacionIngreso { get; set; }
        public bool MarcacionSalida { get; set; }
        public bool SalidaLounch { get; set; }
        public bool RegresoLounch { get; set; }
        public string CodMarcacionIngreso { get; set; }
        public string CodMarcacionSalida { get; set; }
        public string CodSalidaLounch { get; set; }
        public string CodRegresoLounch { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
    }
}
