//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_canasta_basica
    {
        public int Anio { get; set; }
        public decimal valorCanasta { get; set; }
        public double MultiploCanastaBasica { get; set; }
        public double MultiploFraccionBasica { get; set; }
        public string Observacion { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaTansaccion { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
    }
}
