//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_PrestamoMasivo_Det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCarga { get; set; }
        public int Secuencia { get; set; }
        public Nullable<decimal> IdPrestamo { get; set; }
        public decimal IdEmpleado { get; set; }
        public string IdRubro { get; set; }
        public double Monto { get; set; }
        public int NumCuotas { get; set; }
    
        public virtual ro_empleado ro_empleado { get; set; }
        public virtual ro_prestamo ro_prestamo { get; set; }
        public virtual ro_PrestamoMasivo ro_PrestamoMasivo { get; set; }
        public virtual ro_rubro_tipo ro_rubro_tipo { get; set; }
    }
}
