//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ColaCorreo
    {
        public int IdEmpresa { get; set; }
        public decimal IdCorreo { get; set; }
        public string Codigo { get; set; }
        public string Destinatarios { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public string Parametros { get; set; }
        public string IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Error { get; set; }
    }
}
