//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_facturas_eventos
    {
        public int IdEmpresa { get; set; }
        public string Establecimiento { get; set; }
        public string Puntoemision { get; set; }
        public decimal NumFactura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Evento { get; set; }
        public int Factura { get; set; }
    }
}
