//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LogError
    {
        public decimal IdError { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string IdUsuario { get; set; }
        public string Clase { get; set; }
        public string Metodo { get; set; }
        public string InnerException { get; set; }
    }
}
