//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_importacion_ats_fixed
    {
        public string cedulaRuc { get; set; }
        public Nullable<int> nu_comp { get; set; }
        public int baseImpGrav { get; set; }
        public Nullable<double> valorBaseIva { get; set; }
        public int NoObjIva { get; set; }
        public Nullable<double> total { get; set; }
        public string RUC_LCG { get; set; }
        public System.DateTime fe_factura { get; set; }
    }
}
