//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_AnticiposyNCxCruzar
    {
        public string Tipo { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdTipoCbte_Nota { get; set; }
        public decimal IdCbteCble_Nota { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdProveedor { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string cn_observacion { get; set; }
        public System.DateTime cn_fecha { get; set; }
        public double cn_total { get; set; }
        public double MontoAplicado { get; set; }
        public Nullable<double> Saldo { get; set; }
    }
}
