//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_orden_giro_LiquidacionDeCompras
    {
        public int IdEmpresa { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public System.DateTime co_FechaFactura { get; set; }
        public string co_factura { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Num_Autorizacion { get; set; }
        public string Codigo { get; set; }
        public string Estado { get; set; }
        public double co_total { get; set; }
        public string co_observacion { get; set; }
        public int IdSucursal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public Nullable<System.DateTime> co_FechaContabilizacion { get; set; }
    }
}
