//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_CentroCosto
    {
        public int IdEmpresa { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCostoPadre { get; set; }
        public int IdNivel { get; set; }
        public string cc_Descripcion { get; set; }
        public bool EsMovimiento { get; set; }
        public bool Estado { get; set; }
        public string nv_Descripcion { get; set; }
        public string cc_Descripcion_Padre { get; set; }
    }
}
