//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_anio_fiscal_x_cuenta_utilidad
    {
        public int IdEmpresa { get; set; }
        public int IdanioFiscal { get; set; }
        public string IdCtaCble { get; set; }
        public string pc_Cuenta { get; set; }
        public int IdNivelCta { get; set; }
        public string IdGrupoCble { get; set; }
        public Nullable<int> IdTipoCtaCble { get; set; }
        public string gc_GrupoCble { get; set; }
    }
}
