//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_periodo
    {
        public int IdEmpresa { get; set; }
        public int IdPeriodo { get; set; }
        public int IdanioFiscal { get; set; }
        public int pe_mes { get; set; }
        public System.DateTime pe_FechaIni { get; set; }
        public System.DateTime pe_FechaFin { get; set; }
        public string pe_cerrado { get; set; }
        public string pe_estado { get; set; }
        public int idMes { get; set; }
        public string smes { get; set; }
        public string Nemonico { get; set; }
        public string smesIngles { get; set; }
        public string AnioMes { get; set; }
    }
}
