//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_anio_fiscal_x_tb_sucursal_SinCierre
    {
        public int IdEmpresa { get; set; }
        public int IdanioFiscal { get; set; }
        public int IdSucursal { get; set; }
    }
}
