//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_anio_fiscal_x_cuenta_utilidad
    {
        public int IdEmpresa { get; set; }
        public int IdanioFiscal { get; set; }
        public string IdCtaCble { get; set; }
        public string pc_Cuenta { get; set; }
        public int IdNivelCta { get; set; }
        public string IdGrupoCble { get; set; }
        public Nullable<int> IdTipoCtaCble { get; set; }
        public string gc_GrupoCble { get; set; }
    }
}
