//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_anio_fiscal_masivo
    {
        public int IdanioFiscal { get; set; }
        public System.DateTime af_fechaIni { get; set; }
        public System.DateTime af_fechaFin { get; set; }
        public string af_estado { get; set; }
    }
}
