//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCXC_008
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_tipoDoc { get; set; }
        public string vt_NumFactura { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public decimal IdCobro { get; set; }
        public double dc_ValorPago { get; set; }
        public string tc_descripcion { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public string cr_estado { get; set; }
        public string cr_observacion { get; set; }
        public decimal IdCliente { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Su_Descripcion { get; set; }
        public string IdCobro_tipo { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
    }
}
