//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_MotivoLiquidacionTarjeta_x_tb_sucursal
    {
        public int IdEmpresa { get; set; }
        public decimal IdMotivo { get; set; }
        public int Secuencia { get; set; }
        public int IdSucursal { get; set; }
        public string IdCtaCble { get; set; }
        public string pc_Cuenta { get; set; }
        public string Su_Descripcion { get; set; }
    }
}
