//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_AjusteDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdAjuste { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public string IdUnidadMedida { get; set; }
        public double StockSistema { get; set; }
        public double StockFisico { get; set; }
        public double Ajuste { get; set; }
        public double Costo { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_codigo { get; set; }
        public string IdCategoria { get; set; }
        public int IdLinea { get; set; }
        public string ca_Categoria { get; set; }
        public string nom_linea { get; set; }
    }
}
