//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_transferencia_x_in_movi_inve_agrupada_para_recosteo
    {
        public int IdEmpresa { get; set; }
        public int IdSucursalOrigen { get; set; }
        public string cod_sucursal { get; set; }
        public string nom_sucursal { get; set; }
        public int IdBodegaOrigen { get; set; }
        public string cod_bodega { get; set; }
        public string nom_bodega { get; set; }
        public System.DateTime tr_fecha { get; set; }
    }
}
