//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_UnidadMedida_Equiv_conversion
    {
        public string IdUnidadMedida { get; set; }
        public string cod_alterno { get; set; }
        public string Descripcion { get; set; }
        public string IdUnidadMedida_equiva { get; set; }
        public double valor_equiv { get; set; }
        public string interpretacion { get; set; }
    }
}
