//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_area_x_departamento
    {
        public int IdEmpresa { get; set; }
        public int Secuencia { get; set; }
        public int IdDivision { get; set; }
        public string DivisionDescripcion { get; set; }
        public int IdArea { get; set; }
        public string AreaDescripcion { get; set; }
        public int IdDepartamento { get; set; }
        public string DepartamentoDescripcion { get; set; }
    }
}
