//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_rdep
    {
        public int IdEmpresa { get; set; }
        public int Id_Rdep { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public int pe_anio { get; set; }
        public int IdNomina_Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public long Estado { get; set; }
    }
}
