//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_AjusteImpuestoRentaDet
    {
        public int IdEmpresa { get; set; }
        public decimal IdAjuste { get; set; }
        public int Secuencia { get; set; }
        public decimal IdEmpleado { get; set; }
        public decimal SueldoFechaCorte { get; set; }
        public decimal SueldoProyectado { get; set; }
        public decimal OtrosIngresos { get; set; }
        public decimal IngresosLiquidos { get; set; }
        public decimal GastosPersonales { get; set; }
        public decimal AporteFechaCorte { get; set; }
        public decimal BaseImponible { get; set; }
        public decimal FraccionBasica { get; set; }
        public decimal Excedente { get; set; }
        public decimal ImpuestoFraccionBasica { get; set; }
        public decimal ImpuestoRentaCausado { get; set; }
        public decimal DescontadoFechaCorte { get; set; }
        public decimal LiquidacionFinal { get; set; }
        public string pe_nombreCompleto { get; set; }
    }
}
