//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_rdep
    {
        public int IdEmpresa { get; set; }
        public int Id_Rdep { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public int pe_anio { get; set; }
        public int IdNomina_Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public long Estado { get; set; }
    }
}
