//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_participacion_utilidad
    {
        public System.DateTime pe_FechaIni { get; set; }
        public System.DateTime pe_FechaFin { get; set; }
        public double UtilidadDerechoIndividual { get; set; }
        public double UtilidadCargaFamiliar { get; set; }
        public int IdPeriodo { get; set; }
        public int IdUtilidad { get; set; }
        public string Estado { get; set; }
        public double Utilidad { get; set; }
        public string Observacion { get; set; }
        public int IdEmpresa { get; set; }
        public double BaseUtilidad { get; set; }
    }
}
