//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_Historico_Liquidacion_Vacaciones
    {
        public int IdEmpresa { get; set; }
        public int IdSolicitud { get; set; }
        public decimal IdEmpleado { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Desde { get; set; }
        public Nullable<System.DateTime> Fecha_Hasta { get; set; }
        public Nullable<System.DateTime> Fecha_Retorno { get; set; }
        public string Observacion { get; set; }
        public bool Gozadas { get; set; }
        public Nullable<int> IdLiquidacion { get; set; }
        public Nullable<decimal> IdOrdenPago { get; set; }
        public Nullable<int> IdEmpresa_OP { get; set; }
        public string IdTipo_op { get; set; }
        public Nullable<double> ValorCancelado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Observaciones { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string Estado { get; set; }
    }
}
