//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Solicitud_Vacaciones
    {
        public int IdEmpresa { get; set; }
        public int IdSolicitud { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal IdEmpleado { get; set; }
        public System.DateTime Fecha_Desde { get; set; }
        public System.DateTime Fecha_Hasta { get; set; }
        public System.DateTime Fecha_Retorno { get; set; }
        public string Observacion { get; set; }
        public string IdUsuario_Anu { get; set; }
        public string Estado { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public bool Gozadas { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string em_codigo { get; set; }
        public string Estado_liquidacion { get; set; }
    }
}
