//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWBAN_013
    {
        public int IdEmpresa_pago { get; set; }
        public int IdTipoCbte_pago { get; set; }
        public decimal IdCbteCble_pago { get; set; }
        public string TipoPago { get; set; }
        public string pe_nombreCompleto { get; set; }
        public int IdBanco { get; set; }
        public string ba_descripcion { get; set; }
        public string cb_Cheque { get; set; }
        public string BAN_Observacion { get; set; }
        public decimal IdPersona { get; set; }
        public Nullable<System.DateTime> CXP_Fecha { get; set; }
        public string CXP_Documento { get; set; }
        public string CXP_Observacion { get; set; }
        public double MontoAplicado { get; set; }
        public System.DateTime BAN_Fecha { get; set; }
        public Nullable<decimal> IdCbteCble_cxp { get; set; }
    }
}
