//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCXC_001
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public int secuencial { get; set; }
        public Nullable<int> IdBodega_Cbte { get; set; }
        public decimal IdCbte_vta_nota { get; set; }
        public string dc_TipoDocumento { get; set; }
        public double dc_ValorPago { get; set; }
        public string tc_descripcion { get; set; }
        public Nullable<decimal> IdPersona { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string vt_NumFactura { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public string ObservacionFact { get; set; }
        public string ObservacionCobro { get; set; }
        public Nullable<System.DateTime> cr_fecha { get; set; }
        public string NombreContacto { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string cr_estado { get; set; }
        public string Su_Descripcion { get; set; }
        public string ba_descripcion { get; set; }
        public string cr_NumDocumento { get; set; }
        public Nullable<double> cr_TotalCobro { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> ct_IdCbteCble { get; set; }
    }
}
