//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWCXC_003
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_NumFactura { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_cedulaRuc { get; set; }
        public Nullable<System.DateTime> cr_fecha { get; set; }
        public string cr_NumDocumento { get; set; }
        public string IdCobro_tipo { get; set; }
        public string IdMotivo_tipo_cobro { get; set; }
        public Nullable<double> PorcentajeRet { get; set; }
        public decimal Base { get; set; }
        public string ESRetenIVA { get; set; }
        public string ESRetenFTE { get; set; }
        public string cr_EsElectronico { get; set; }
        public string tc_descripcion { get; set; }
        public string TipoRetencion { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public Nullable<double> dc_ValorPago { get; set; }
    }
}
