//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWFAC_018
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public string Su_Descripcion { get; set; }
        public System.DateTime no_fecha { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<int> IdTipoNota { get; set; }
        public string No_Descripcion { get; set; }
        public string NumNota { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_cedulaRuc { get; set; }
        public double ValorAplicado { get; set; }
        public string NumDocumentoAplica { get; set; }
        public string NumDocumentoReemplazo { get; set; }
        public Nullable<decimal> Subtotal0 { get; set; }
        public Nullable<decimal> SubtotalIVA { get; set; }
        public Nullable<decimal> ValorIva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Estado { get; set; }
        public string NomEstado { get; set; }
        public int Orden { get; set; }
        public string CreDeb { get; set; }
    }
}
