//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWROL_030
    {
        public int IdEmpresa { get; set; }
        public decimal IdRol { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<decimal> IdEmpleado { get; set; }
        public string IdRubro { get; set; }
        public string ca_descripcion { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string rub_codigo { get; set; }
        public string ru_codRolGen { get; set; }
        public Nullable<int> ru_orden { get; set; }
        public string ru_descripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<double> Valor { get; set; }
    }
}
