//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Reportes.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxxx
    {
        public int IdEmpresa { get; set; }
        public string em_ruc { get; set; }
        public string em_nombre { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<double> c303 { get; set; }
        public Nullable<double> c353 { get; set; }
        public Nullable<double> c304 { get; set; }
        public Nullable<double> c354 { get; set; }
        public Nullable<double> c307 { get; set; }
        public Nullable<double> c357 { get; set; }
        public Nullable<double> c308 { get; set; }
        public Nullable<double> c358 { get; set; }
        public Nullable<double> c309 { get; set; }
        public Nullable<double> c359 { get; set; }
        public Nullable<double> c310 { get; set; }
        public Nullable<double> c360 { get; set; }
        public Nullable<double> c311 { get; set; }
        public Nullable<double> c361 { get; set; }
        public Nullable<double> c312 { get; set; }
        public Nullable<double> c362 { get; set; }
        public Nullable<double> c3120 { get; set; }
        public Nullable<double> c3620 { get; set; }
        public Nullable<double> c314 { get; set; }
        public Nullable<double> c364 { get; set; }
        public Nullable<double> c319 { get; set; }
        public Nullable<double> c369 { get; set; }
        public Nullable<double> c320 { get; set; }
        public Nullable<double> c370 { get; set; }
        public Nullable<double> c322 { get; set; }
        public Nullable<double> c372 { get; set; }
        public Nullable<double> c323 { get; set; }
        public Nullable<double> c373 { get; set; }
        public Nullable<double> c324 { get; set; }
        public Nullable<double> c374 { get; set; }
        public Nullable<double> c325 { get; set; }
        public Nullable<double> c375 { get; set; }
        public Nullable<double> c326 { get; set; }
        public Nullable<double> c376 { get; set; }
        public Nullable<double> c327 { get; set; }
        public Nullable<double> c377 { get; set; }
        public Nullable<double> c328 { get; set; }
        public Nullable<double> c378 { get; set; }
        public Nullable<double> c329 { get; set; }
        public Nullable<double> c379 { get; set; }
        public Nullable<double> c330 { get; set; }
        public Nullable<double> c380 { get; set; }
        public Nullable<double> c331 { get; set; }
        public Nullable<double> c332 { get; set; }
        public Nullable<double> c333 { get; set; }
        public Nullable<double> c383 { get; set; }
        public Nullable<double> c334 { get; set; }
        public Nullable<double> c384 { get; set; }
        public Nullable<double> c335 { get; set; }
        public Nullable<double> c385 { get; set; }
        public Nullable<double> c336 { get; set; }
        public Nullable<double> c386 { get; set; }
        public Nullable<double> c337 { get; set; }
        public Nullable<double> c387 { get; set; }
        public Nullable<double> c338 { get; set; }
        public Nullable<double> c388 { get; set; }
        public Nullable<double> c339 { get; set; }
        public Nullable<double> c389 { get; set; }
        public Nullable<double> c340 { get; set; }
        public Nullable<double> c390 { get; set; }
        public Nullable<double> c341 { get; set; }
        public Nullable<double> c391 { get; set; }
        public Nullable<double> c342 { get; set; }
        public Nullable<double> c392 { get; set; }
        public Nullable<double> c343 { get; set; }
        public Nullable<double> c393 { get; set; }
        public Nullable<double> c344 { get; set; }
        public Nullable<double> c394 { get; set; }
        public Nullable<double> c345 { get; set; }
        public Nullable<double> c395 { get; set; }
        public Nullable<double> c346 { get; set; }
        public Nullable<double> c396 { get; set; }
        public double c423 { get; set; }
    }
}
